# Lab 2 - Performing Indexing, Slicing and Broadcasting in Numpy

# Program 1 - Indexing in NumPy

In [4]:
import numpy as np

In [10]:
arr=np.arange(1,10,2)
print("Elements of array:",arr)
arr1=arr[np.array([4,0,2,-1,-2])]
print("Indexed Elemnts of array arr:",arr1)

Elements of array: [1 3 5 7 9]
Indexed Elemnts of array arr: [9 1 5 9 7]


In [16]:
print("Array arr1:",arr1)
print("Array 1:",arr1[0])
print("Array 2:",arr1[1])
print("Array 3:",arr1[2])
print("Array 4:",arr1[3])
print("Array 5:",arr1[4])


Array arr1: [9 1 5 9 7]
Array 1: 9
Array 2: 1
Array 3: 5
Array 4: 9
Array 5: 7


In [18]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
arr1=arr.reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
print("Element 1st row and 3column index:",arr1[1,3])

Element 1st row and 3column index: 7


In [24]:
print("Element index:",arr1[2,1])

Element index: 9


In [25]:
print("Element index:",arr1[1,0])

Element index: 4


In [26]:
print("Element index:",arr1[0,2])

Element index: 2


In [27]:
print("Element index:",arr1[1,1])

Element index: 5


In [37]:
arr=np.arange(12)
arr
arr1=arr.reshape(2,2,3)
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [31]:
print("Element index:",arr1[1,0,2])

Element index: 8


In [38]:
print("Element 0 array, 1 row and 1 column index:",arr1[0,1,1])

Element 0 array, 1 row and 1 column index: 4


# Program 2 - Slicing in Arrays

In [42]:
arr=np.arange(6)
print(arr)
arr[1:5]

[0 1 2 3 4 5]


array([1, 2, 3, 4])

In [62]:
arr=np.arange(12)
arr
arr1=arr.reshape(3,4)
print (arr1)
print("Elements of 1st row and 1st column upto last column\n",arr1[1:2,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Elements of 1st row and 1st column upto last column
 [[5 6]]


In [69]:
arr=np.arange(1,10)
arr
arr1=arr.reshape(3,3)
print (arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [75]:
scalar=10
result=arr1+scalar
print(result)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
